import React, { Fragment, memo, useMemo } from 'react';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  Box,
  Text,
  Icon,
  useColorModeValue,
} from '@chakra-ui/react';
import { Link, usePage } from '@inertiajs/react';
import { useMemoizedCallback } from '@/Hooks';

/**
 * Performance-Optimized Breadcrumbs Component
 * Provides contextual navigation with automatic path detection
 */

export interface BreadcrumbItem {
  label: string;
  href?: string;
  icon?: React.ComponentType;
  isCurrentPage?: boolean;
  onClick?: () => void;
}

export interface BreadcrumbsProps {
  items?: BreadcrumbItem[];
  separator?: React.ReactElement | string;
  maxItems?: number;
  showHomeIcon?: boolean;
  className?: string;
  variant?: 'default' | 'financial' | 'compact';
  autoGenerate?: boolean;
}

export const Breadcrumbs: React.FC<BreadcrumbsProps> = memo(({
  items,
  separator,
  maxItems = 5,
  showHomeIcon = true,
  className,
  variant = 'default',
  autoGenerate = true,
}) => {
  const { url } = usePage();
  
  // Memoized color values
  const linkColor = useColorModeValue('blue.600', 'blue.300');
  const currentColor = useColorModeValue('gray.700', 'gray.200');
  const mutedColor = useColorModeValue('gray.500', 'gray.400');

  // Memoized auto-generated breadcrumbs from URL
  const autoGeneratedItems = useMemo(() => {
    if (!autoGenerate || items) return [];

    const pathSegments = url.split('/').filter(Boolean);
    const breadcrumbItems: BreadcrumbItem[] = [];

    // Add home/dashboard
    if (showHomeIcon) {
      breadcrumbItems.push({
        label: 'Dashboard',
        href: '/dashboard',
        icon: () => (
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/>
          </svg>
        ),
      });
    }

    // Generate breadcrumbs from path segments
    let currentPath = '';
    pathSegments.forEach((segment, index) => {
      currentPath += `/${segment}`;
      const isLast = index === pathSegments.length - 1;
      
      // Format segment label (capitalize and replace hyphens/underscores)
      const label = segment
        .replace(/[-_]/g, ' ')
        .replace(/\b\w/g, l => l.toUpperCase());

      breadcrumbItems.push({
        label,
        href: isLast ? undefined : currentPath,
        isCurrentPage: isLast,
      });
    });

    return breadcrumbItems;
  }, [url, autoGenerate, items, showHomeIcon]);

  // Use provided items or auto-generated ones
  const breadcrumbItems = items || autoGeneratedItems;

  // Memoized truncated items if exceeding maxItems
  const displayItems = useMemo(() => {
    if (breadcrumbItems.length <= maxItems) {
      return breadcrumbItems;
    }

    const firstItem = breadcrumbItems[0];
    const lastItems = breadcrumbItems.slice(-2);
    const ellipsisItem: BreadcrumbItem = {
      label: '...',
      isCurrentPage: false,
    };

    return [firstItem, ellipsisItem, ...lastItems];
  }, [breadcrumbItems, maxItems]);

  // Memoized click handler
  const handleItemClick = useMemoizedCallback((item: BreadcrumbItem) => {
    if (item.onClick) {
      item.onClick();
    }
  }, []);

  // Memoized variant styles
  const variantStyles = useMemo(() => {
    const styles = {
      default: {
        fontSize: 'sm',
        spacing: 2,
      },
      financial: {
        fontSize: 'sm',
        spacing: 3,
        bg: useColorModeValue('blue.50', 'blue.900'),
        px: 3,
        py: 2,
        borderRadius: 'md',
        borderLeft: '3px solid',
        borderLeftColor: 'blue.400',
      },
      compact: {
        fontSize: 'xs',
        spacing: 1,
      },
    };
    return styles[variant];
  }, [variant]);

  // Memoized breadcrumb items rendering
  const renderedItems = useMemo(() => 
    displayItems.map((item, index) => {
      const isLast = index === displayItems.length - 1;
      const isEllipsis = item.label === '...';

      return (
        <Fragment key={`${item.label}-${index}`}>
          <BreadcrumbItem isCurrentPage={item.isCurrentPage || isLast}>
            {item.href && !item.isCurrentPage ? (
              <BreadcrumbLink
                as={Link}
                href={item.href}
                color={linkColor}
                fontSize={variantStyles.fontSize}
                _hover={{ textDecoration: 'underline' }}
                onClick={() => handleItemClick(item)}
              >
                <Fragment>
                  {item.icon && (
                    <Icon as={item.icon} mr={1} boxSize={4} />
                  )}
                  {item.label}
                </Fragment>
              </BreadcrumbLink>
            ) : (
              <Text
                color={isEllipsis ? mutedColor : currentColor}
                fontSize={variantStyles.fontSize}
                fontWeight={isLast && !isEllipsis ? 'medium' : 'normal'}
                cursor={isEllipsis ? 'default' : 'text'}
              >
                <Fragment>
                  {item.icon && !isEllipsis && (
                    <Icon as={item.icon} mr={1} boxSize={4} />
                  )}
                  {item.label}
                </Fragment>
              </Text>
            )}
          </BreadcrumbItem>
          
          {!isLast && (
            <BreadcrumbSeparator color={mutedColor}>
              {separator || '/'}
            </BreadcrumbSeparator>
          )}
        </Fragment>
      );
    }),
    [
      displayItems,
      linkColor,
      currentColor,
      mutedColor,
      variantStyles.fontSize,
      separator,
      handleItemClick,
    ]
  );

  if (displayItems.length === 0) {
    return null;
  }

  return (
    <Box className={className} {...(variant === 'financial' ? variantStyles : {})}>
      <Breadcrumb spacing={variantStyles.spacing}>
        {renderedItems}
      </Breadcrumb>
    </Box>
  );
});

Breadcrumbs.displayName = 'Breadcrumbs';

/**
 * Financial Breadcrumbs with specialized styling
 */
export const FinancialBreadcrumbs: React.FC<Omit<BreadcrumbsProps, 'variant'>> = memo((props) => (
  <Breadcrumbs {...props} variant="financial" />
));

FinancialBreadcrumbs.displayName = 'FinancialBreadcrumbs';

/**
 * Compact Breadcrumbs for dense layouts
 */
export const CompactBreadcrumbs: React.FC<Omit<BreadcrumbsProps, 'variant'>> = memo((props) => (
  <Breadcrumbs {...props} variant="compact" />
));

CompactBreadcrumbs.displayName = 'CompactBreadcrumbs';

export default Breadcrumbs;
